"""lecture_notes

Revision ID: 38cd957100b4
Revises: b8e3d6f1c742
Create Date: 2026-06-20 14:56:28.825447
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38cd957100b4'
down_revision: Union[str, None] = 'b8e3d6f1c742'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecture_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('kind', sa.Enum('LINK', 'PDF', 'SLIDES', 'SUMMARY', name='note_kind'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['class_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lecture_notes_session_id'), 'lecture_notes', ['session_id'], unique=False)
    # (autogenerate also flagged an attendance_final.sessions NOT NULL drift from
    # another dev's model — out of scope for this migration; left untouched.)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lecture_notes_session_id'), table_name='lecture_notes')
    op.drop_table('lecture_notes')
    op.execute('DROP TYPE IF EXISTS note_kind')
    # ### end Alembic commands ###
