"""live_meeting tables

Revision ID: 3a0dd075c00f
Revises: 64f290eb783a
Create Date: 2026-06-20 02:06:35.665215
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a0dd075c00f'
down_revision: Union[str, None] = '64f290eb783a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmarks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp_ms', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['class_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookmarks_session_id'), 'bookmarks', ['session_id'], unique=False)
    op.create_index(op.f('ix_bookmarks_user_id'), 'bookmarks', ['user_id'], unique=False)
    op.create_table('cue_cards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('shown_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['class_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cue_cards_session_id'), 'cue_cards', ['session_id'], unique=False)
    op.create_table('leaderboard_points',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['class_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leaderboard_points_session_id'), 'leaderboard_points', ['session_id'], unique=False)
    op.create_index(op.f('ix_leaderboard_points_user_id'), 'leaderboard_points', ['user_id'], unique=False)
    op.create_table('notices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['class_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notices_session_id'), 'notices', ['session_id'], unique=False)
    op.create_table('pinned_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('pinned_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pinned_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['class_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', name='uq_pinned_message_session')
    )
    op.create_index(op.f('ix_pinned_messages_session_id'), 'pinned_messages', ['session_id'], unique=False)
    op.create_table('polls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='poll_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['class_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_polls_session_id'), 'polls', ['session_id'], unique=False)
    op.create_table('quizzes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('time_limit_secs', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'LIVE', 'ENDED', name='quiz_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['class_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quizzes_session_id'), 'quizzes', ['session_id'], unique=False)
    op.create_table('poll_responses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('poll_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('option_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poll_id', 'user_id', name='uq_poll_response_poll_user')
    )
    op.create_index(op.f('ix_poll_responses_poll_id'), 'poll_responses', ['poll_id'], unique=False)
    op.create_index(op.f('ix_poll_responses_user_id'), 'poll_responses', ['user_id'], unique=False)
    op.create_table('quiz_questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('quiz_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('correct_index', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_questions_quiz_id'), 'quiz_questions', ['quiz_id'], unique=False)
    op.create_table('quiz_responses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('selected_index', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'user_id', name='uq_quiz_response_question_user')
    )
    op.create_index(op.f('ix_quiz_responses_question_id'), 'quiz_responses', ['question_id'], unique=False)
    op.create_index(op.f('ix_quiz_responses_user_id'), 'quiz_responses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_responses_user_id'), table_name='quiz_responses')
    op.drop_index(op.f('ix_quiz_responses_question_id'), table_name='quiz_responses')
    op.drop_table('quiz_responses')
    op.drop_index(op.f('ix_quiz_questions_quiz_id'), table_name='quiz_questions')
    op.drop_table('quiz_questions')
    op.drop_index(op.f('ix_poll_responses_user_id'), table_name='poll_responses')
    op.drop_index(op.f('ix_poll_responses_poll_id'), table_name='poll_responses')
    op.drop_table('poll_responses')
    op.drop_index(op.f('ix_quizzes_session_id'), table_name='quizzes')
    op.drop_table('quizzes')
    op.drop_index(op.f('ix_polls_session_id'), table_name='polls')
    op.drop_table('polls')
    op.drop_index(op.f('ix_pinned_messages_session_id'), table_name='pinned_messages')
    op.drop_table('pinned_messages')
    op.drop_index(op.f('ix_notices_session_id'), table_name='notices')
    op.drop_table('notices')
    op.drop_index(op.f('ix_leaderboard_points_user_id'), table_name='leaderboard_points')
    op.drop_index(op.f('ix_leaderboard_points_session_id'), table_name='leaderboard_points')
    op.drop_table('leaderboard_points')
    op.drop_index(op.f('ix_cue_cards_session_id'), table_name='cue_cards')
    op.drop_table('cue_cards')
    op.drop_index(op.f('ix_bookmarks_user_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_session_id'), table_name='bookmarks')
    op.drop_table('bookmarks')
    # Drop ENUM types so a later upgrade can recreate them cleanly.
    op.execute('DROP TYPE IF EXISTS quiz_status')
    op.execute('DROP TYPE IF EXISTS poll_status')
    # ### end Alembic commands ###
